'use strict';
// Solve bkb / kbg so every KO target (SPEC §5.2 / §5A) is met, per style. See
// game/ko.cjs for the measurement. Single-target moves keep their designed base
// knockback and solve the growth; moves with a center + ledge target solve both.
// Writes game/styles/<style>-kb.generated.cjs and prints the table.
// Usage: node tools/calibrate.cjs [style ...]
const fs=require('node:fs'),path=require('node:path');
const KO=require('../game/ko.cjs'),M=require('../game/match.cjs');
const only=process.argv.slice(2);
function boxesOf(style,id){
  const mv=M.STYLES[style].moves[id];
  if(id==='bthrow')return {key:'hit',boxes:[mv.hit]};
  if(mv.type==='counter')return {key:'counter',boxes:[mv.counter.hit]};
  if(mv.type==='inhale')return {key:'spit',boxes:[mv.spit.hit]};
  if(mv.type==='shot')return {key:'proj:'+mv.spawn.type,boxes:[M.STYLES[style].projectiles[mv.spawn.type].hit]};
  return {key:'0',boxes:mv.hitboxes};
}
const set=(style,id,bkb,kbg)=>{for(const b of boxesOf(style,id).boxes){b.bkb=bkb;b.kbg=kbg;}};
function solveKbg(t,bkb){
  let lo=5,hi=400;
  for(let i=0;i<30;i++){const mid=(lo+hi)/2;set(t.style,t.move,bkb,mid);const got=KO.measure(t);if(got===null||got>t.percent)lo=mid;else hi=mid;}
  set(t.style,t.move,bkb,hi);return hi;
}
const report=[];
const styles=[...new Set(KO.TARGETS.map(t=>t.style))].filter(s=>!only.length||only.includes(s));
for(const style of styles){
  const out={},byMove={};
  for(const t of KO.TARGETS.filter(t=>t.style===style))(byMove[t.move]??=[]).push(t);
  for(const [id,targets] of Object.entries(byMove)){
    const {key,boxes}=boxesOf(style,id);let best;
    if(targets.length===1){const bkb=boxes[0].bkb;best={bkb,kbg:solveKbg(targets[0],bkb)};}
    else{
      for(let bkb=10;bkb<=120;bkb+=2){const kbg=solveKbg(targets[0],bkb);const second=KO.measure(targets[1]);const err=second===null?1e9:Math.abs(second-targets[1].percent);if(!best||err<best.err)best={bkb,kbg,err};}
    }
    set(style,id,best.bkb,best.kbg);out[id]={[key]:{bkb:best.bkb,kbg:+best.kbg.toFixed(2)}};
    for(const t of targets)report.push({流派:style,目标:t.label,设计:t.percent,实测:KO.measure(t),bkb:best.bkb,kbg:+best.kbg.toFixed(2)});
  }
  const file=path.join(__dirname,`../game/styles/${style}-kb.generated.cjs`);
  fs.writeFileSync(file,"'use strict';\n// Generated by tools/calibrate.cjs — do not edit by hand. Re-run `npm run calibrate`\n// after changing a move's damage, angle, frames or a KO target.\nmodule.exports="+JSON.stringify(out,null,2)+";\n");
}
console.table(report);
